blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.home, name='home'),
    path('blog/', views.post_list, name='post_list'),
    path('blog/<str:slug>/', views.post_detail, name='post_detail'),
    path('contact/', views.contact_page, name = 'contact_page'),
    # path('post/<str:slug>/comment/', views.add_comment_to_post, name='add_comment_to_post'),
]

newsletter/urls.py
from django.urls import path
from . import views

app_name='newsletter'

urlpatterns = [
	path('subscribe', views.newsletter_subscribe, name='subscribe'),
]

poetry/urls.py
from django.contrib import admin
from django.conf import settings 
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('story/', include('story.urls')),
    path('thoughts', include('thoughts.urls')),
    path('newsletter/', include('newsletter.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('videos/', include('videos.urls'))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

story/urls.py
from django.urls import path
from . import views

app_name = 'story'

urlpatterns = [
 	path('story/', views.story_list, name='story_list'),
   	path('detail/<str:slug>/', views.story_detail, name='story_detail'),
]

thoughts/urls.py
from django.urls import path
from . import views

app_name = 'thoughts'

urlpatterns = [
 	path('thoughts/', views.thoughts_list, name='thoughts_list'),
   	path('detail/<str:slug>/', views.thoughts_detail, name='thoughts_detail'),
]

videos/urls.py
from django.urls import path
from . import views

app_name = 'videos'

urlpatterns = [
	path('videos/', views.video_list, name='video_list'),
   	path('detail/<str:slug>/', views.video_detail, name='video_detail'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User



STATUS=(
	(0, "Draft"),
	(1,"Publish")
	)

class Post(models.Model):
	title=models.CharField(max_length=200, unique=True)
	slug = models.SlugField(max_length=200,unique=True)
	author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
	image = models.ImageField(upload_to='images/', blank=True)
	updated_on =models.DateTimeField(auto_now=True)
	content = models.TextField(blank=True)
	created_on = models.DateTimeField(auto_now_add=True)
	status = models.IntegerField(choices=STATUS, default=0)


	class Meta:
		ordering=['-created_on']

	def __str__(self):
		return self.title

	# def get_absolute_url(self): #may be i can change this using reverse method
	# 	return f"/blog/{self.slug}"


class Comment(models.Model):
    name = models.CharField(max_length=200)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    # approved_comment = models.BooleanField(default=False)
    post = models.ForeignKey(Post,on_delete=models.CASCADE, related_name='comments')

    class Meta:
        ordering = ['created_on']

    # def approve(self):
    #     self.approved_comment = True
    #     self.save()

    def __str__(self):
        return 'Comment {} by {}'.format(self.body, self.name)

blog/forms.py
from django import forms
from .models import Comment

# class ContactForm(forms.Form):
# 	name = forms.CharField(required = True, widget=forms.TextInput(attrs={
# 		'class':'control'
# 		}))
# 	email = forms.EmailField(required = True, widget=forms.EmailInput(attrs={
# 		'class':'control'
# 		}))
# 	message = forms.CharField(required = True,
# 							widget=forms.Textarea(attrs={
# 								'class':'control'
# 								})
# 							)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'body')
        widgets={
        	'name':forms.TextInput(attrs = {'class':'control'}),
        	'body':forms.Textarea(attrs={'class': 'control'})
        }

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from . models import Post, Comment
from django.http import HttpResponse, HttpResponseRedirect
from django.utils import timezone
from .forms import CommentForm
from django.db.models import Q
from story.models import Story
from thoughts.models import Thoughts

def home(request):
	total_poems = Post.objects.all().count()
	total_story = Story.objects.all().count()
	total_thoughts = Thoughts.objects.all().count()
	posts = Post.objects.filter(status=1).order_by('-created_on')[:3]
	story = Story.objects.filter(status=1).order_by('-created_on')[:3]
	thoughts = Thoughts.objects.filter(status=1).order_by('-created_on')[:3]
	return render(request=request,
				template_name='blog/home.html',
				context= {'posts': posts,
							'stories': story,
							'thoughts': thoughts,
							'total_poems':total_poems,
							'total_story':total_story,
							'total_thoughts':total_thoughts})
	#I can use model from different aap here
	#and use them in home.html template
	#to show the home page list from different model

def post_list(request):
	posts = Post.objects.filter(status=1).order_by('-created_on')
	return render(request, 'blog/post_list.html',{'posts': posts})

def post_detail(request, slug):
	posts = Post.objects.get(slug=slug)

	if request.method == "POST":
		form = CommentForm(request.POST)
		if form.is_valid():
			comment = Comment(
				name = form.cleaned_data["name"],
				body = form.cleaned_data["body"],
				post = posts
				)
			comment.save()
			form = CommentForm()
	else:
		form = CommentForm() 

	comments = Comment.objects.filter(post=posts)
	context = {
				'posts': posts,
				'comments':comments,
				'form': form,
				}

	return render(request, 'blog/post_detail.html', context)

#backend for receiving detail is yet to be set
def contact_page(request):
	context = {}
	return render(request, "blog/contact_page.html", context)

blog/templates/blog/contact_page.html
{% extends 'blog/index.html' %}
	
{% block content %}

	<section class="section" style="text-align: center; height: auto; min-height: 100vh;">
		<div class="conainer">
			<div style="margin-top: 30px; border:solid;">
				<p style="font-size: 24px;">Hi, I will be happy to connet to you:</p>
				<br>
				
				<br>
				<p style="font-family:helvetica; font-size: 20px;">Please write a mail to me <a href="mailto:bhashadiaries@gmail.com">here</a></p>
				<br>
				
				<p style="font-size: 20px"> Or </p>
				
				<br>
				<p style="font-family: arial; font-size: 20px;">Connect to me through my fb page using messanger <br> or whatsapp option
					<a href="https://www.facebook.com/bhaskarpandey806/" target="_blank">
						here
					</a>
				</p>
				<br>
			</div>
			
		</div>
	</section> 


{% endblock %}

  <!-- <form method="POST" style="padding:12px">{% csrf_token %}
			<h4 style="text-align: center;">Contact me here</h4>
				{{ form.as_p }}
			<button type="submit">send</button>
		</form> -->

	


<!-- is-link -->

blog/templates/blog/home.html
{% extends 'blog/index.html' %}
{% load static %}

{% block content %}

<section class="section" id="home" style="height:auto; min-height: 100vh;">

	<div class="container">
		<div class="columns is-centered">
			
			<div class="column">
				
				<figure style="text-align: center">
					<img style="max-width: 40%; border-radius: 20%" src={% static "images/logo.png" %}>
					<figcaption style="text-align: center;color:#282828; font-size: 16px;">
						एक संगम- &nbsp मेरी 	भावनाओं, अनुभवों और विचारों का
					</figcaption>
					<br>
				</figure>

				<!-- subscriber form starts here -->

				<form style="padding:3px;text-align:center;" action="https://tinyletter.com/bhashadiaries" method="post" target="popupwindow" onsubmit="window.open('https://tinyletter.com/bhashadiaries', 'popupwindow', 'scrollbars=yes,width=800,height=600');return true">

					<div class="field">
						<!-- <label for="tlemail" class="title is-5">Subscribe for newsletters</label> -->	
					<p style="color: black; font-size: 20px">Subscribe for newsletters</p>
					</div>

					<div class="field">
  						<div class="control" style="text-align: center;">
   							<input class="input" type="email" name="email" id="tlemail" placeholder="Enter your email" style="width: 60%">

   							<input type="hidden" value="1" name="embed"/>

   							<button class="button is-primary">Subscribe</button>
  						</div>
					</div>
				</form>
				<!-- subscriber form ends here
 -->
			</div>

			

			<hr>
			
			<div class="column" style="text-align: center;">
				<p style="font-size: 20px; color: black">
					मैं अनभिज्ञ हूँ,<br>
					हर वाद से प्रतिवाद से,<br>
					प्रेम की हर बात से।<br>
					विरह के इक संवाद से,<br>
					मैं अनभिज्ञ हूँ।।<br>
					है ये मेरी बस कल्पना,<br>
					शब्द जो भी लिख रहा।<br>
					है भला क्या प्रेम ये,<br>
					मुझको ना ये दिख रहा।।<br>
					तेरा संग होना है जरूरी,<br>
					कि रच सकूँ इक काव्य मैं।।<br>
					ना कर सका कंठस्थ इतना,<br>
					कि लिख सकूँ सिर्फ याद से।।<br>
					मैं अनभिज्ञ हूँ,<br>
					हर वाद से प्रतिवाद से,<br>
					प्रेम की हर बात से।।<br>
				</p>
			</div>
		
		</div>
	</div>
  
</section>

<section class="section" id="about" style="background-color: rgb(244,248,252); min-height: 100vh;">
	<div class="container">
		<h1 class="title is-3" style="text-align: center; text-decoration-line: underline;">परिचय</h1>
		<div class="columns is-centered">


			<div class="column" style="text-align: center;">
				<figure>
					<img style="max-width: 50%; border-radius: 40%; box-shadow:  4px -4px 8px;" src={% static "images/bhasker.jpg" %}>
					<figcaption>Bhaskar Pandey</figcaption>
				</figure>
			</div>

			<div class="column" style="text-align: center;">
				<div><h1 class="title is-2"><span id="b">bhasha</span><span id="d">diaries<span></h1>
				</div>
				<p style="font-size: 16px;">एक संगम - मेरी भावनाओं, अनुभवों और विचारों का ।</p>
				<br>
				<p style="font-size: 20px;">यह पेज मेरी भावनाओं, अनुभवों और विचारों को शब्दों मे गढकर<br> आपके समक्ष रखने की एक कोशिश है।<br>
					आशा करता हूँ इन भावों को आप तक पहुंचाने में सफल रहूँगा ।<br> 
					भूल होना प्रकृति है, अतः मुझमें सुधार लाने हेतु आपके सुझाओं का स्वागत है,<br>
					आपके अमूल्य विचार और  सुझावों के लिए मैं आपका आभारी रहूँगा ।
				</p>
			</div>
			
		</div>

	</div>

</section>

<section class="section" id="recent-articles" style="background-color: rgb(244,248,252);">
	<div class="container">
		<h1 class="title is-3" style="text-align: center;">
			Recent Poems 
			<a href="{% url 'blog:post_list' %}">({{total_poems}})</a>
		</h1>
		<div class="columns">
		{%for post in posts%}
			<div class="column is-one-third" style="text-align: center;">
			
				<div class="card box box-shadow-lift" style="height: 100%;display: flex; flex-direction: column; padding: 0.8rem;">
  					<style >
						.card:hover{
							box-shadow: 1px 8px 20px grey;
						}
  					</style>
					{%if post.image%}
	  					<div class="card-image">
  							
							<figure class="image is-4by3">
  								<img src="{{ post.image.url}}" alt="{{ post.title }}">
							</figure>
  				
  						</div>
  					{%endif%}
	  		
	  				<div class="card-content">

		        		<p class="title" style="">{{post.title}}</p>
		        		<p class="subtitle" style="font-size: 15px;">{{post.created_on}}</p>

		        		<p>{{post.content|safe|striptags|truncatewords:25}}</p>
		        		
		        		<a href={% url 'blog:post_detail' post.slug %}> continue reading...</a>
		      
	      			</div>

	      			<footer class="card-footer" style="margin-top: auto">
    					<p class="card-footer-item">
      						<span>Share on<br> <a href="whatsapp://send?text=https://bhashadiaries.pythonanywhere.com/blog/{{post.slug}}/">Whatsapp</a></span>
      					</p>
    					<p class="card-footer-item">
      						<span> Share on<br> <a href="https://www.facebook.com/sharer/sharer.php?u=https://bhashadiaries.pythonanywhere.com/blog/{{post.slug}}/" target="_blank">Facebook</a></span>
      					</p>

      					<p class="card-footer-item">
      						<span> Share on<br> <a href="https://twitter.com/intent/tweet?text=https://bhashadiaries.pythonanywhere.com/blog/{{post.slug}}/" target="_blank">Twitter</a></span>
      					</p>
	  				</footer>

	  			</div>
			</div>

		{% endfor %}
		</div>

		{%if thoughts%}
			<h1 class="title is-3" style="text-align: center;">
				Recent Musings
				<a href="{% url 'thoughts:thoughts_list' %}">({{total_thoughts}})</a>
			</h1>
			<div class="columns">
				{%for thought in thoughts%}
					<div class="column is-one-third" style="text-align: center;">
			
						<div class="card box box-shadow-lift" style="height: 100%;display: flex;
								flex-direction: column; padding: 0.8rem;">
								<style >
								.card:hover{
									box-shadow: 1px 8px 20px grey;
								}
								</style>
							{%if thought.image%}
		  					<div class="card-image">
	  							
								<figure class="image is-4by3">
	  								<img src="{{ thought.image.url}}" alt="{{ post.title }}">
								</figure>
	  				
	  						</div>
	      					{%endif%}
	  		
		  					<div class="card-content">

				        		<p class="title" style="">{{thought.title}}</p>
				        		<p class="subtitle" style="font-size: 15px;">{{thought.created_on}}</p>
				        		<p>{{thought.content|safe|striptags|truncatewords:25}}</p>
				        		
				        		<a href={% url 'thoughts:thoughts_detail' thought.slug %}> continue reading...</a>
			      
			      			</div>

		      				<footer class="card-footer" style="margin-top: auto">
		    					<p class="card-footer-item">
		      						<span>Share on<br> <a href="whatsapp://send?text=https://bhashadiaries.pythonanywhere.com/thoughtsdetail/{{thought.slug}}/">Whatsapp</a></span>
		      					</p>
		    					<p class="card-footer-item">
		      						<span> Share on<br> <a href="https://www.facebook.com/sharer/sharer.php?u=https://bhashadiaries.pythonanywhere.com/thoughtsdetail/{{thought.slug}}/" target="_blank">Facebook</a></span>
		      					</p>

		      					<p class="card-footer-item">
		      						<span> Share on<br> <a href="https://twitter.com/intent/tweet?text=https://bhashadiaries.pythonanywhere.com/thoughtsdetail/{{thought.slug}}/" target="_blank">Twitter</a></span>
		      					</p>
		  					</footer>

	  					</div>
					</div>

				{% endfor %}
			</div>
		{%endif%}
	
		{%if stories%}
			<h1 class="title is-3" style="text-align: center;">
				Recent Story
				<a href="{% url 'story:story_list' %}">({{total_story}})</a>

			</h1>
			<div class="columns">
			{%for story in stories%}
				<div class="column is-one-third" style="text-align: center;">
		
					<div class="card box box-shadow-lift" style="height: 100%;display: flex;
							flex-direction: column; padding: 0.8rem;">
							<style >
							.card:hover{
								box-shadow: 1px 8px 20px grey;
							}
							</style>
						{%if post.image%}
		  					<div class="card-image">
									
								<figure class="image is-4by3">
										<img src="{{ story.image.url}}" alt="{{ post.title }}">
								</figure>
					
							</div>
	  					{%endif%}
			
	  					<div class="card-content">

			        		<p class="title" style="">{{story.title}}</p>
			        		<p class="subtitle" style="font-size: 15px;">{{story.created_on}}</p>
			        		<p>{{story.content|safe|striptags|truncatewords:25}}</p>
			        		
			        		<a href={% url 'story:story_detail' story.slug %}> continue reading...</a>
		      
		      			</div>

	      				<footer class="card-footer" style="margin-top: auto">
							<p class="card-footer-item">
	  							<span>Share on <br> <a href="whatsapp://send?text=https://bhashadiaries.pythonanywhere.com/story/detail/{{story.slug}}/">Whatsapp</a></span>
	  						</p>
							<p class="card-footer-item">
	  							<span> Share on<br> <a href="https://www.facebook.com/sharer/sharer.php?u=https://bhashadiaries.pythonanywhere.com/story/detail/{{story.slug}}/" target="_blank">Facebook</a></span>
	  						</p>
	  						<p class="card-footer-item">
	      						<span> Share on<br> <a href="https://twitter.com/intent/tweet?text=https://bhashadiaries.pythonanywhere.com/story/detail/{{story.slug}}/" target="_blank">Twitter</a></span>
	      					</p>
							</footer>

						</div>
				</div>

			{% endfor %}
			</div>
		{%endif%}
	</div>

	
</section>

{% endblock %}

blog/templates/blog/index.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <title> bhashadiaries </title>
      <link rel="stylesheet" href="{% static 'css/blog.css' %}">
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.2/css/bulma.min.css">
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
      
  </head>


  <body class="has-navbar-fixed-top">
    <!-- fb comment integration javascript sdk -->
      <div id="fb-root"></div>
      <script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v7.0">
      </script>
      
    <nav class="navbar is-grey is-fixed-top" role="navigation" aria-label="main navigation">
      <div class="navbar-brand" style="max-height: 3.5rem">
        <a class="navbar-item" id="brand" href="{% url 'blog:home' %}" style="font-size: 40px; font-weight: bold"><span id="b">bhasha</span><span id="d">diaries<span></a>
          <style>
            
            #b{
              color: #143D59;
            }
            
            #d{
              color: #F4B41A;
            }
            #brand:hover{
              background-color: black;

          </style>
        <a role="button" class="navbar-burger burger" id="hamburger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </a>
        <style>


          #hamburger:hover{
             background-color: black;
             color: white;
          }
        </style>

      </div>

      <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
            <a class="navbar-item" id="navbar-inline" href="{% url 'blog:home' %}">Home</a>
            <a class="navbar-item" id="navbar-inline" href="{% url 'blog:post_list' %}">Poems</a>
            <a class="navbar-item" id="navbar-inline" href="{% url 'thoughts:thoughts_list' %}">Musings</a>
            <a class="navbar-item" id="navbar-inline" href="{% url 'story:story_list' %}">Stories</a>
            <a class="navbar-item" id="navbar-inline" href="{% url 'videos:video_list' %}">Videos</a>
            <a class="navbar-item" id="navbar-inline" href="http://bhashadiaries.pythonanywhere.com/#about">About</a>
            <a class="navbar-item" id="navbar-inline" href="{% url 'blog:contact_page' %}">Contact</a>
          <style>
            #navbar-inline:hover{
              background-color:black !important;
              color:white !important;
            }
          </style>
        </div>

        <div class="navbar-end">
          <div class="navbar-item" id="subscribe-button">
            <div class="buttons">
              <a class="button is-primary" id="subscribe" href="{% url 'newsletter:subscribe' %}">
                <strong>Subscribe</strong>
              </a>
              <style>
                #subscribe-button:hover{
                  background-color: black;
                }
                #subscribe:hover{
                  background-color: white;
                  color:black;
                }
              </style>
              
            </div>
          </div>
        </div>
      </div>
    </nav>
    
      {%block content%}

      {%endblock%}
  
    


    <footer class="footer" style="background-color: black; padding: 2rem 1.5rem 2rem;">
      <div class="container">
        <hr style="height: 5px; background-color: black">
        <div class="columns is-mobile is-multiline is-centered">

          <div class="column is-half-mobile" style="text-align: center;">
            <h1 class="title is-5" style="color:white">Quick links</h1>
            <ul>
              <li><a href="{% url 'blog:home' %}">Home</a></li>
              <li><a href="{% url 'blog:post_list' %}">Poems</a></li>
              <li><a href="{% url 'thoughts:thoughts_list' %}">Musings</a></li>
              <li><a href="{% url 'story:story_list' %}">Stories</a></li>
              <li><a href="{% url 'videos:video_list' %}">Videos</a></li>
              <li><a href="http://bhashadiaries.pythonanywhere.com/#about">About</a></li>
              <li> <a href="mailto:bhashadiaries@gmail.com">contact</a></li>
            </ul>
          </div>

          <div class="column is-half-mobile" style="text-align: center;">
            <h1 class="title is-5" style="color:white">
              Follow on
            </h1>
            <ul>
              <li>
                <a href="https://www.facebook.com/bhaskarpandey806/" target="_blank">
                  <i class="fab fa-facebook fa-2x"></i>
                </a>
              </li>
              <li>
                <a href="https://www.instagram.com/bhasha806/" target="_blank">
                  <i class="fab fa-instagram fa-2x"></i>
                </a>
              </li>
              <li>
                <a href="https://twitter.com/bhasha806?s=08" target="_blank">
                  <i class="fab fa-twitter-square fa-2x"></i>
                </a>
              </li>
            </ul>
          </div>

      </div>
      <div style="text-align: center;">
        <h1 class="title is-5" style="color:white"> Copyright by   &copy;Bhasha 2020</h1>
        <h1 class="title is-6" style="color:white">Developed by: <a href="mailto:randheer.dakshana15@gmail.com">Randheer</a></h1>
      </div>

    </div>
    </footer>

<script type="text/javascript">
  document.addEventListener('DOMContentLoaded', () => {

  const $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);

  if ($navbarBurgers.length > 0) {


    $navbarBurgers.forEach( el => {
      el.addEventListener('click', () => {

        const target = el.dataset.target;
        const $target = document.getElementById(target);

        el.classList.toggle('is-active');
        $target.classList.toggle('is-active');

      });
    });
  }

});
</script>
  </body>
</html>

blog/templates/blog/post_detail.html
{%extends 'blog/index.html' %}

{% block content %}
	
	<section class="section" style="background-color: rgb(244,248,252); text-align: center; min-height: 100vh;">
		<div class="container">
			<article class="article">
				<p class="title is-3">{{posts.title}}</p>
				<p class="subtitle is-6">{{posts.created_on}}</p>
				{%if posts.image%}
				<figure class="image is-6by3">
	      			<img src="{{ posts.image.url}}" alt="{{ post.title }}">
	    		</figure>
	    		{%endif%}
				<p>{{posts.content|safe}} </p>
			</article>

			<!-- sharing on social media starts here -->
			<p style="margin-top: 50px"><span style="font-style: bold; font-size: 24px"> Share On:</span> 
				<!-- whatsapp sharing code starts here -->
				<a href="whatsapp://send?text=https://bhashadiaries.pythonanywhere.com/blog/{{posts.slug}}/">
					<i class="fab fa-whatsapp-square fa-2x"></i>
				</a>
				<!-- whatsapp sharing code ends here -->

				<a href="https://www.facebook.com/sharer/sharer.php?u=https://bhashadiaries.pythonanywhere.com/blog/{{posts.slug}}/" target="_blank">
 					<i class="fab fa-facebook fa-2x"></i>
				</a>

				<a href="https://twitter.com/intent/tweet?text=https://bhashadiaries.pythonanywhere.com/blog/{{posts.slug}}/" target="_blank">
 					<i class="fab fa-twitter-square fa-2x"></i>
				</a>

			</p>
			<!-- sharing on social media code ends here -->

			<hr style="border: 1px solid black; margin:60px 0 30px 0">
			
			<h3 class="title is-4">Leave a comment:</h3>

		<!-- fb comment integrations -->
			<div class="fb-comments" data-href="https://bhashadiaries.pythonanywhere.com/blog/{{posts.slug}}/" data-numposts="5" data-width=""></div>


		<!-- fb integration ends here -->

		<!-- comment system made by me starts here -->
			<!-- <form action="{% url 'blog:post_detail' posts.slug %}" method="post">{% csrf_token %}

				<div class="control" style="text-align: center;">
					{% for field in form %}
						<label class="label">{{field.label_tag}}</label>
						{{field}}
					{% endfor %}
				</div>
		       
		        <div class="control" style="text-align: center;">
	    			<button class="button is-primary">Submit</button>
	  			</div>
	 
	    	</form>

	    	<h3 class="title is-4">Comments:</h3>
		    {% for comment in comments %}
			    <p>
			        On {{comment.created_on }}&nbsp;
			        <b>{{ comment.name }}</b> wrote:
			    </p>
			    <p>{{ comment.body }}</p>
			    <br>
		    {% endfor %} -->

		<!-- comment system made by ends here -->
		</div>

	</section>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/index.html' %}
	

<!-- this will list musings on musings -->
	{% block content %}
		<section class="section" style="background-color: rgb(244,248,252); min-height: 100vh;">
			<div class="columns is-multiline">
				{% for post in posts %}
					<div class="column is-one-third" style="text-align: center;">
					
						<div class="card box box-shadow-lift" style="height: 100%;display: flex; flex-direction: column; padding: 0.8rem;">
	  						<style >
	  							.card:hover{
	  								box-shadow: 1px 8px 20px grey;
	  							}
	  						</style>

							{%if post.image%}
			  					<div class="card-image">
		  							
									<figure class="image is-4by3">
		  								<img src="{{ post.image.url}}" alt="{{ post.title }}">
									</figure>
		  				
		  						</div>
	      					{%endif%}
			  		
			  				<div class="card-content">

			  					<p class="title" ><a href="{% url 'blog:post_detail' post.slug %}">{{post.title}}</a></p> 

				        		<p class="subtitle" style="font-size: 15px;">{{post.created_on}}</p>


				        		<p>{{post.content|safe|striptags|truncatewords:25}}</p>
				        		<!-- {{post.content|safe|linebreaks|truncatewords:80}}  -->

				        		<a href="{%url 'blog:post_detail' post.slug %}">continue reading...</a> 

			      			</div>
			      			<footer class="card-footer" style="margin-top:auto">
		    					<p class="card-footer-item">
		      						<span>Share on<br> <a href="whatsapp://send?text=https://bhashadiaries.pythonanywhere.com/blog/{{post.slug}}/">Whatsapp</a></span>
		      					</p>
		    					<p class="card-footer-item">
		      						<span> Share on<br> <a href="https://www.facebook.com/sharer/sharer.php?u=https://bhashadiaries.pythonanywhere.com/blog/{{post.slug}}/" target="_blank">Facebook</a></span>
		      					</p>

		      					<p class="card-footer-item">
		      						<span> Share on<br> <a href="https://twitter.com/intent/tweet?text=https://bhashadiaries.pythonanywhere.com/blog/{{post.slug}}/" target="_blank">Twitter</a></span>
		      					</p>
		  					</footer>

			  			</div>
					</div>
				{% endfor %}
			</div>
		</section>
	{% endblock content %}