blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.home, name='home'),
    path('blog/', views.post_list, name='post_list'),
    path('blog/<str:slug>/', views.post_detail, name='post_detail'),
    path('contact/', views.contact_page, name = 'contact_page'),
    # path('post/<str:slug>/comment/', views.add_comment_to_post, name='add_comment_to_post'),
]

poetry/urls.py
from django.contrib import admin
from django.conf import settings 
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('story/', include('story.urls')),
    path('thoughts', include('thoughts.urls')),
    path('newsletter/', include('newsletter.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('videos/', include('videos.urls'))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

videos/urls.py
from django.urls import path
from . import views

app_name = 'videos'

urlpatterns = [
	path('videos/', views.video_list, name='video_list'),
   	path('detail/<str:slug>/', views.video_detail, name='video_detail'),
]

videos/models.py
from django.db import models
from django.contrib.auth.models import User

STATUS=(
	(0, "Draft"),
	(1,"Publish")
	)

class Video(models.Model):
	title=models.CharField(max_length=200, unique=True)
	slug = models.SlugField(max_length=200,unique=True)
	author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='video')
	video = models.FileField(upload_to='videos/', blank=True)
	video_description = models.TextField()
	updated_on =models.DateTimeField(auto_now=True)
	created_on = models.DateTimeField(auto_now_add=True)
	status = models.IntegerField(choices=STATUS, default=0)


	class Meta:
		ordering=['-created_on']
		verbose_name ='video'
		verbose_name_plural ='videos'

	def __str__(self):
		return self.title

videos/views.py
from django.shortcuts import render
from . models import Video

def video_list(request):
	posts = Video.objects.filter(status=1).order_by('-created_on')
	return render(request,'videos/video_list.html',{'posts':posts})


def video_detail(request,slug):
	posts = Video.objects.get(slug=slug)
	return render(request, 'videos/video_detail.html',{'posts':posts})

videos/templates/videos/video_detail.html
{%extends 'blog/index.html' %}

{% block content %}
	
	<section class="section" style="background-color: rgb(244,248,252); text-align: center; min-height: 100vh;">
		
		<div class="container">
			
			<article class="article">
				<p class="title is-3">{{posts.title}}</p>
				<p class="subtitle is-6">{{posts.created_on}}</p>
				{%if posts.video %}
					<video width="500" controls>
					  <source src="{{ posts.video.url}}" type="video/mp4">
					</video>
	    		{%endif%}
				<p>{{posts.video_description|safe}} </p>
			</article>

			<!-- sharing on social media starts here -->
			<p style="margin-top: 50px"><span style="font-style: bold; font-size: 24px"> Share On:</span>
				<!-- whatsapp sharing code starts here -->
				<a href="whatsapp://send?text=https://bhashadiaries.pythonanywhere.com/story/detail/{{posts.slug}}/">
					<i class="fab fa-whatsapp-square fa-2x"></i>
				</a>
				<!-- whatsapp sharing code ends here -->

				<a href="https://www.facebook.com/sharer/sharer.php?u=https://bhashadiaries.pythonanywhere.com/story/detail/{{posts.slug}}/" target="_blank">
 					<i class="fab fa-facebook fa-2x"></i>
				</a>

				<a href="https://twitter.com/intent/tweet?text=https://bhashadiaries.pythonanywhere.com/story/detail/{{posts.slug}}/" target="_blank">
 					<i class="fab fa-twitter-square fa-2x"></i>
				</a>
			</p>
			<!-- sharing on social media code ends here -->

			<hr style="border: 1px solid black; margin:60px 0 30px 0">
			
			<h3 class="title is-4">Leave a comment:</h3>

		<!-- fb comment integrations -->
			<div class="fb-comments" data-href="https://bhashadiaries.pythonanywhere.com/videos/detail/{{posts.slug}}/" data-numposts="5" data-width=""></div>

		</div>
	</section>
{% endblock %}

videos/templates/videos/video_list.html
{% extends 'blog/index.html' %}
	

<!-- this will list some limited post on homepage -->
	{% block content %}
		<section class="section" style="background-color: rgb(244,248,252); min-height: 100vh;">
			<!-- <h1 class="title is-3" style="text-align: center; color:#3498DB;">My videos:</h1> -->
			<div class="columns is-multiline">
			{% for post in posts %}
				<div class="column is-one-third" style="text-align: center;">
				
					<div class="card box box-shadow-lift" style="height: 100%;display: flex; flex-direction: column; padding: 0.8rem;">
  						<style >
							.card:hover{
								box-shadow: 1px 8px 20px grey;
							}
  						</style>

						{%if post.video%}
		  					<div class="card-image">
      							<!-- <img src="{{ post.video.url}}" alt="{{ post.title }}"> -->
      							<video width="500" controls>
					  				<source src="{{ post.video.url}}" type="video/mp4">
								</video>
      						</div>
      					{%endif%}

		  		
		  				<div class="card-content">				

		  					<p class="title is-3" style=""><a href="{% url 'videos:video_detail' post.slug %}">{{post.title}}</a></p> 

			        		<p class="subtitle" style="font-size: 15px;">{{post.created_on}}</p>
			        		<p>{{post.video_description|safe|slice:":200"}}</p>
			        		<p style="margin-top:2rem"><a href="{% url 'videos:video_detail' post.slug %}">continue watching...</a></p> 

			        		<!-- <p>let user viewe number of comments here</p> -->
			      
		      			</div>

	      				<footer class="card-footer" style="margin-top: auto">
    						<p class="card-footer-item">
      							<span>Share on<br> <a href="whatsapp://send?text=https://bhashadiaries.pythonanywhere.com/story/detail/{{post.slug}}/">Whatsapp</a></span>
      						</p>
    						<p class="card-footer-item">
      							<span> Share on<br> <a href="https://www.facebook.com/sharer/sharer.php?u=https://bhashadiaries.pythonanywhere.com/story/detail/{{post.slug}}/" target="_blank">Facebook</a></span>
      						</p>
      						<p class="card-footer-item">
	      						<span> Share on<br> <a href="https://twitter.com/intent/tweet?text=https://bhashadiaries.pythonanywhere.com/{{post.slug}}/" target="_blank">Twitter</a></span>
	      					</p>
  						</footer>
	  					</div>
					</div>

			{% endfor %}
		</div>
		</section>
	{% endblock content %}